config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'
  
  resources :users, only: [:show, :index]
  resources :feeds, only: [:index]
  resources :todos, only: [:index, :create, :destroy] do 
    member do
      post :upvote
      post :downvote
      post :follow
      post :unfollow
    end
    resources :items, only: [:create, :destroy] do
      member do
        post :check
      end
    end
    resources :todo_comments, only: [:create, :destroy, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :todo
  belongs_to :user

  validates :content, presence: true 
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  has_many :users_todos, dependent: :destroy
  has_many :users, through: :users_todos, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :todo_comments, dependent: :destroy

  validates :title, presence: true
end

app/models/todo_comment.rb
class TodoComment < ApplicationRecord
  belongs_to :user
  belongs_to :todo

  validates_presence_of [:body]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :users_todos, dependent: :destroy
  has_many :followed_todos, through: :users_todos, source: :todo, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :todo_comments, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,  presence: true, length: { minimum: 4, maximum: 14 }
end

app/models/users_todo.rb
class UsersTodo < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :todo

  validates :rating, numericality: { greater_than_or_equal_to: -1 }
  validates :rating, numericality: { less_than_or_equal_to: 1 }
  validates :user_id, uniqueness: { scope: :todo_id }

  after_save :recalculate_rating

  def recalculate_rating 
    todo.update(rating: todo.votes.sum(:rating))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache) }
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feed_todos = current_user.followed_todos
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_todo, only: [:create, :destroy, :check]

  def create
    @item = @todo.items.create(item_params.merge({user_id: current_user.id}))
    if @item.save
      redirect_to request.referrer 
    else
      flash[:danger] = "ops"
      redirect_to request.referrer 
    end
  end

  def destroy
    @item = @todo.items.find(params[:id]).destroy
    redirect_to request.referrer 
  end

  def check
    @item = @todo.items.find(params[:id])
    @item.update(checkbox: !@item.checkbox)
    redirect_to request.referrer
  end

  private

    def set_todo
      @todo = Todo.find(params[:todo_id])
    end

    def item_params
      params.require(:item).permit(:content, :checkbox)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/todo_comments_controller.rb
class TodoCommentsController < ApplicationController
  before_action :set_todo_list, only: [:create, :update, :destroy]

  def create
    @todo_comment = @todo.todo_comments.create(todo_comments_params.merge({user_id: current_user.id}))
    if @todo_comment.save
      redirect_to request.referrer 
    else
      redirect_to request.referrer 
    end
  end
  
  def update
    @todo_comment = @todo.todo_comments.find(params:[:id])
    if @todo_comment.update(todo_comments_params)
      redirect_to @todo
    end
  end

  def destroy
    @todo_comment = @todo.todo_comments.find(params:[:id]).destroy
    redirect_to request.referrer
  end

  private

  def set_todo_list
    @todo = Todo.find(params[:todo_id])
  end

    def todo_comments_params
      params.require(:todo_comment).permit(:body)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :find_todo, only: [:upvote, :downvote, :follow, :unfollow]

  def index
    @todos = current_user.todos
    @todos = @todos.order("rating DESC")
  end

  def create
    @todo = current_user.todos.create(todo_params) 
    if @todo.save
      redirect_to request.referrer 
    else
      flash[:danger] = "ops"
    end
  end

  def destroy
    todo = Todo.find(params[:id]).destroy
    flash[:success] = "List deleted!"
    redirect_to request.referrer 
  end

  def upvote
    vote = Vote.find_or_create_by(user_id: current_user.id, todo_id: @todo.id)
    vote.update(rating: 1)
    redirect_to request.referrer 
  end
  
  def downvote
    vote = Vote.find_or_create_by(user_id: current_user.id, todo_id: @todo.id)
    vote.update(rating: -1)
    redirect_to request.referrer 
  end

  def follow
    UsersTodo.find_or_create_by(user_id: current_user.id, todo_id: @todo.id)
    redirect_to request.referrer 
  end

  def unfollow
    users_todo = UsersTodo.find_by(user_id: current_user.id, todo_id: @todo.id)
    unless users_todo.nil?
      users_todo.destroy
    end
    redirect_to request.referrer 
  end

  private
  
    def find_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:title, :checkable, :rating)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder

  def to_turbo_stream
    controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end
  
  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all    
    @users = @users.paginate(:page => params[:page], :per_page => 11) 
  end

  def show
    @user = User.find(params[:id])
    @todos = @user.todos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_comments_helper.rb
module TodoCommentsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/turbo_devise_helper.rb
module TurboDeviseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/todos/_todo.html.erb
<% if todo.title.present? %>
  <div class="card border-secondary rounded-0">
    <h6 class="card-title text-center mt-3 font-monospace">
      <%= todo.title %>
      | Рейт:  
        <%= todo.rating %> ( 
        <%= link_to "+", upvote_todo_path(id: todo.id), data: { turbo_method: :post }, class: "main-nav__link" %>
        <%= link_to "-", downvote_todo_path(id: todo.id), data: { turbo_method: :post }, class: "main-nav__link" %> )
    </h6>
    <div class="card-body">
      <ul>
        <% todo.items.each.with_index(1) do |item, index| %>
          <%= render 'todos/items/item', todo: todo, item: item, index: index %>
        <% end %>
      </ul>
        <%= render 'todos/items/items_form', todo: todo %>
    </div>
  </div>
  <div class="mb-4">
    <%= link_to "Destroy", todo_path(id: todo.id, user_id: params[:id]), data: { turbo_method: :delete }, class: "btn btn-outline-secondary btm-sm border-top-0 rounded-0" %>
  </div>
<% end %> 

app/views/todos/_todos_form.html.erb
<%= form_for(Todo.new, url: todos_path) do |f| %> 
    <ul>
      <li>
        <h3><%= f.label "New category of list:", class: "font-monospace mb-2" %></h3>
        <div class="input-group-text rounded-0 p-0 border-0", style="max-width: 40rem;">
          <div class="input-group-prepend">
            <%= f.check_box  :checkable, class: "btn-check btn-outline-secondary" %>
            <%= f.label      :checkable, "Checkable", class:"btn btn-outline-dark btn-check-2-dark rounded-0" %>
            <%= f.text_field :title, class: "form-input text-center", style: "width: 115%; height: 38px;" %>
          </div>
        </div>
      </li>
    </ul>
  <%= f.submit "Create", class: "btn btn-outline-dark w-100 rounded-0" %>
<% end %>

app/views/todos/index.html.erb
<%= content_for :title do %>
  <div class="page-header__title">
    <span class="branch">
      SCAMLIST
    </span>
  </div>
<% end %>

<%= render 'layouts/header' %>

<turbo-frame id="todos">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <%= render 'todos/todos_form' %> 
      </div>
      <div class="col-sm-8">
        <% @todos.each do |todo| %>
          <%= render 'todos/todo', todo: todo %>
        <% end %>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/todos/items/_item.html.erb
<li>
  <% if todo.checkable %>
    <%= link_to check_todo_item_path(todo_id: todo.id, id: item.id), data: { turbo_method: :post }, class: "main-nav__link" do %>
      <% if item.checkbox %>
        <i class="bi bi-x-square"></i>
      <% else %>
        <i class="bi bi-square"></i>
      <% end %>
    <% end %>
  <% end %>
  <%= index %>. <%= item.content %>
  <%= link_to "Destroy", todo_item_path(todo_id: todo.id, id: item.id), data: { turbo_method: :delete }, class: "text-decoration-none" %>
</li>

app/views/todos/items/_items_form.html.erb
<%= form_for(todo.items.new, url: todo_items_path(todo_id: todo.id)) do |f| %>
  <div class="mb-3">
    <%= f.text_field :content, class: "form-input mt-4 text-center" %>
  </div>
  <%= f.submit "Create", class: "btn btn-outline-dark w-100 rounded-0" %>
<% end %>

app/views/todos/todo_comments/_todo_comment.html.erb
<div class="ml-3">
  <ul>
    <% todo.todo_comments.each do |comment| %>
      <li>
        <%= comment.user.name %>: <%= comment.body %>
      </li>
    <% end %>
  </ul>
</div>

app/views/todos/todo_comments/_todo_comments_form.html.erb
<%= form_for(todo.todo_comments.new, url: todo_todo_comments_path(todo_id: todo.id)) do |f| %>
  <div class="mb-3">
    <%= f.label "write your comment:", class: "form-label" %>
    <%= f.text_field :body, class: "form-input text-center" %>
  </div>
  <%= f.submit "Post", class: "btn btn-outline-secondary w-100 rounded-0" %>
<% end %>

app/views/users/index.html.erb
<%= content_for :title do %>
  <div class="page-header__title">
    <span class="branch">
      users
    </span>
  </div>
<% end %>

<%= render 'layouts/header' %>

<turbo-frame id="users">
  <div class="container mb-2">
    <div class="row">
      <div class="col align-self-start">
      <h4 class='font-monospace'>
        Scam accomplices
      </h4>
      </div>
      <div class="col align-self-end">
        <div class="shadow-none w-50">
          <% @users.each do |user| %>
            <div class="card border-dark bg-white border-1 mb-4 rounded-0 shadow-none">
              <div class="card-header bg-white text-center">
                <%= link_to user.name, user_path(id: user.id), class: "text-dark" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col align-self-center font-monospace">
        <%= will_paginate %>
      </div>
      <div class="col align-self-end mb-3">
      </div>
    </div>
  </div>
</turbo-frame>

app/views/users/show.html.erb
<%= content_for :title do %>
  <div class="page-header__title">
    <span class="branch">
      profile
    </span>
  </div>
<% end %>

<%= render 'layouts/header' %>
<turbo-frame id="users">
  <div class="container mb-2">
    <div class="row">
      <div class="col align-self-start">
        <h3 class='font-monospace'>
          <%= @user.name %>
        </h3>
        <ul class="mt-4">
          <% @user.todos.each do |todo|%>
            <%= render 'todos/todo', todo: todo %>
            <% unless @user.id == current_user.id %>
              <div id="follow_form">
                  <%= link_to "unfollow", unfollow_todo_path(id: todo.id), data: { turbo_method: :post }, class: "main-nav__link" %> 
                  <%= link_to "follow", follow_todo_path(id: todo.id), data: { turbo_method: :post }, class: "main-nav__link" %> 
              </div>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="col align-self-end mb-3">
      </div>
    </div>
  </div>
</turbo-frame>