config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'
  
  resources :users, only: [:show, :index]
  resources :feeds, only: [:index]
  resources :todos, only: [:index, :create, :destroy] do 
    member do
      post :upvote
      post :downvote
      post :follow
      post :unfollow
    end
    resources :items, only: [:create, :destroy] do
      member do
        post :check
      end
    end
    resources :todo_comments, only: [:create, :destroy, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :todo
  belongs_to :user

  validates :content, presence: true 
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  has_many :users_todos, dependent: :destroy
  has_many :users, through: :users_todos, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :todo_comments, dependent: :destroy

  validates :title, presence: true
end

app/models/todo_comment.rb
class TodoComment < ApplicationRecord
  belongs_to :user
  belongs_to :todo

  validates_presence_of [:body]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :users_todos, dependent: :destroy
  has_many :followed_todos, through: :users_todos, source: :todo, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :todo_comments, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,  presence: true, length: { minimum: 4, maximum: 14 }
end

app/models/users_todo.rb
class UsersTodo < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :todo

  validates :rating, numericality: { greater_than_or_equal_to: -1 }
  validates :rating, numericality: { less_than_or_equal_to: 1 }
  validates :user_id, uniqueness: { scope: :todo_id }

  after_save :recalculate_rating

  def recalculate_rating 
    todo.update(rating: todo.votes.sum(:rating))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache) }
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feed_todos = current_user.followed_todos
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_todo, only: [:create, :destroy, :check]

  def create
    @item = @todo.items.create(item_params.merge({user_id: current_user.id}))
    if @item.save
      redirect_to request.referrer 
    else
      flash[:danger] = "ops"
      redirect_to request.referrer 
    end
  end

  def destroy
    @item = @todo.items.find(params[:id]).destroy
    redirect_to request.referrer 
  end

  def check
    @item = @todo.items.find(params[:id])
    @item.update(checkbox: !@item.checkbox)
    redirect_to request.referrer
  end

  private

    def set_todo
      @todo = Todo.find(params[:todo_id])
    end

    def item_params
      params.require(:item).permit(:content, :checkbox)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :find_todo, only: [:upvote, :downvote, :follow, :unfollow]

  def index
    @todos = current_user.todos
    @todos = @todos.order("rating DESC")
  end

  def create
    @todo = current_user.todos.create(todo_params) 
    if @todo.save
      redirect_to request.referrer 
    else
      flash[:danger] = "ops"
    end
  end

  def destroy
    todo = Todo.find(params[:id]).destroy
    flash[:success] = "List deleted!"
    redirect_to request.referrer 
  end

  def upvote
    vote = Vote.find_or_create_by(user_id: current_user.id, todo_id: @todo.id)
    vote.update(rating: 1)
    redirect_to request.referrer 
  end
  
  def downvote
    vote = Vote.find_or_create_by(user_id: current_user.id, todo_id: @todo.id)
    vote.update(rating: -1)
    redirect_to request.referrer 
  end

  def follow
    UsersTodo.find_or_create_by(user_id: current_user.id, todo_id: @todo.id)
    redirect_to request.referrer 
  end

  def unfollow
    users_todo = UsersTodo.find_by(user_id: current_user.id, todo_id: @todo.id)
    unless users_todo.nil?
      users_todo.destroy
    end
    redirect_to request.referrer 
  end

  private
  
    def find_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:title, :checkable, :rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all    
    @users = @users.paginate(:page => params[:page], :per_page => 11) 
  end

  def show
    @user = User.find(params[:id])
    @todos = @user.todos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todo_comments_helper.rb
module TodoCommentsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/turbo_devise_helper.rb
module TurboDeviseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="mt-5">
  <header class="page-header">
    <div class="page-header__logo">
      <a href="/" class="page-header__logo-link main-nav__link--active">
        <span class="page-header__logo-row">Scam</span> 
        <span class="page-header__logo-row">App</span>
      </a>
    </div> 
    <nav class="main-nav">
      <ul class="main-nav__list">
        <li class="main-nav__list-item">
          <%= link_to "Feed", feeds_path, class: "main-nav__link"%>
        </li>
        <li class="main-nav__list-item">
          <%= link_to "Users", users_path, class: "main-nav__link"%>
        </li>
        <li class="main-nav__list-item">
          <%= link_to "Profile", current_user, class: "main-nav__link"%>
        </li>
        <li class="main-nav__list-item">
          <%= link_to "Scam list", todos_path, class: "main-nav__link"%>
        </li>
        <li class="main-nav__list-item">
          <%= link_to "Settings",  edit_user_registration_path(current_user), class: "main-nav__link" %>
        </li>
        <li class="main-nav__list-item">
          <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "main-nav__link"%>
        </li>
      </ul>
    </nav> 
    <%= content_for :title %>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScamApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>